### PR TITLE
Another Hello

### PR DESCRIPTION
**Pull request by caohhung**

### CODE REVIEW

**Comment by caohhung** [comment]
ok to test

**Comment by ghost** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/chhung/job/a-alakazam-zuul/3/ : SUCCESS in 0s
- https://cing-dev.intgdc.com/job/chhung/job/a-alakazam-compliance/2/ : SUCCESS in 0s

**Comment by caohhung** [comment]
ok to test

**Comment by ghost** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/chhung/job/a-alakazam-zuul/4/ : SUCCESS in 0s
- https://cing-dev.intgdc.com/job/chhung/job/a-alakazam-compliance/3/ : SUCCESS in 0s

**Comment by caohhung** [comment]
ok to test

**Comment by ghost** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/chhung/job/a-alakazam-zuul/5/ : SUCCESS in 0s
- https://cing-dev.intgdc.com/job/chhung/job/a-alakazam-compliance/4/ : SUCCESS in 2s

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://cing-dev.intgdc.com/job/chhung/job/a-alakazam-zuul/6/ : SUCCESS in 0s

**Pull request merged**
